name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Set the Node.js version you're using
        
      # Step 3: Install dependencies using `npm ci`
      - name: Install dependencies
        run: npm ci
        
      # Step 4: Build the site (outputs to `dist/` folder)
      - name: Build the site
        run: npm run build
        
      # Step 5: Deploy to GitHub Pages using `peaceiris/actions-gh-pages`
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "dist"
          publish_branch: "deployment"