name: Run tests

on:
  pull_request:
    types: [opened, edited]
    branches:
      - main  # Trigger the workflow on pull requests to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Set the Node.js version you're using
        
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
        
      # Step 4: Run tests
      - name: Build the site
        run: npm run test